import "./globals.scss";
import "react-toastify/dist/ReactToastify.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import ModalProvider from "./context/ModalProvider";
import Header from "./components/Header";
import AuthProvider from "./context/AuthProvider";
import AdminsSidebar from "./components/Admin.sidebar";
import Dashboard from "./components/Dashboard";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ModalProvider>
          <AuthProvider>
            <>
              <div id="root">
              <Header />
              <Dashboard />
                {children}
              </div>
            </>
          </AuthProvider>
        </ModalProvider>
        <ToastContainer theme="colored" position="top-center" />
      </body>
    </html>
  );
}
